# Generated by Django 3.1 on 2021-07-18 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20210718_0430'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GenreFilmWork',
            new_name='FilmWorkGenre',
        ),
    ]
